### ISSUE TITLE
Tutorials Page formatting is incorrect

### ISSUE THREAD

**Issue by m4n4n-j** [AFLplusplus/Website#5]
The page at [https://aflplus.plus/docs/tutorials/](https://aflplus.plus/docs/tutorials/) is not properly formatted. The content is scattered all around and users are unable to see the links and other materials shared there.
![image](https://user-images.githubusercontent.com/49025960/159547453-13a93012-4678-4d93-a73d-e5d95bcbba26.png)

**Comment by fockboi-lgtm** [comment]
I guess something went build process, I guess it should be fixed in the next time the website updates.

**Comment by VARUN-009** [comment]
I wanna work on this issue. Please assign this to me and since I'm new to this repo so I request you to please guide me through

**Comment by m4n4n-j** [comment]
> I wanna work on this issue. Please assign this to me and since I'm new to this repo so I request you to please guide me through

It is fine now
